### ISSUE TITLE
Пересобрал проект сам, теперь работает на Win10

### ISSUE THREAD

**Issue by sstyle** [merlokk/CO2Meter#10]
В проекте небыло иконки, поставил другую. Теперь все работает и в гугл заливает
[OnlineLogger.zip](https://github.com/merlokk/CO2Meter/files/2208915/OnlineLogger.zip)

**Comment by merlokk** [comment]
Added, thanks!
https://github.com/merlokk/CO2Meter/releases/tag/Release
