### ISSUE TITLE
Does not upload file to Google Drive. SSL Error

### ISSUE THREAD

**Issue by sstyle** [merlokk/CO2Meter#5]
![2015-04-28 14 34 47](https://cloud.githubusercontent.com/assets/6489964/7368880/3a95d9f4-edb5-11e4-94a8-8add76d39c5e.png)

![2015-04-28 13 56 10](https://cloud.githubusercontent.com/assets/6489964/7368883/48b0049c-edb5-11e4-8ff6-0af7b891be33.png)

And there is no uploaded file in G.Drive

**Comment by merlokk** [comment]
OpenSSL dll files needs to be installed https://www.openssl.org/related/binaries.html  or just placed near exe file http://indy.fulgan.com/SSL/

**Comment by sstyle** [comment]
ок, теперь ошибки нет. Но все равно файла нет в драйве. Сначала пишет data count: 1 ниже Data sent.... а потом снова count: 0.

**Comment by merlokk** [comment]
google clientID и clientSecret правильные?

**Comment by sstyle** [comment]
разумеется. скопипастил с гугла. перепроверял чтобы без пробелов на краях было

**Comment by merlokk** [comment]
а вот это все правильно?
It needs to create a new project with rights to:

Drive API
Google Cloud Storage
Google Cloud Storage JSON API

And then create Client ID for native application
And then copy CLIENT ID and CLIENT SECRET
Do not forget to fill the field PRODUCT NAME into APIs & auth/consent screen

особенно последнее - без него не работает.

А я завтра запущу - гляну - может они чтото поменяли

**Comment by sstyle** [comment]
права на апи - да, там по умолчанию все апи включены, эти в том числе.
Когда создавал ключи. там было три варианта веб приложение, еще какое-то и я выбрал последний вариант отдельное приложение, там были варианты хром, плейстейшн и тд, я указал "другое". создалось, сверху написано "Client ID for native application" а ниже ключ и логин. Название тоже указал, там этот шаг вобще пропустить нельзя, и когда появлятся окно запроса прав, сверху это название написано.

**Comment by sstyle** [comment]
было бы здорово какой нибудь виджет запилить или еще как-то чтобы текущие показания выводились. на айфон вобще здорово. а то я полагаю там будет здоровая таблица со строками?

**Comment by sstyle** [comment]
открыл проекты в гугле, пишет errors: 198 в моем проекте

**Comment by sstyle** [comment]
файл появился, оказывается Drive API был выключен. Но data count: 0, он залил в файл старые строки, а новые пока что не идут. на самом девайсе надо включить логгирование, чтобы rec писал?

**Comment by merlokk** [comment]
Вроде должен и онлайн данные писать. он там их в файл сохраняет если не может в гугл отправить. на всякий случай можно проверить - открыть СОМ порт о попробовать туда ввести команду ":"  (https://github.com/merlokk/CO2Meter/wiki/Protocol)  если оно ответит текущими значениями - значит не надо нажимать кнопку LOG - все должно работать и так

**Comment by sstyle** [comment]
ну может быть на пол секунды данные и появляются а потом исчезают, а я имею ввиду чтобы они оставались в программе крупно и обновлялись. То есть сидя за компом было бы удобно видеть текущие значения на приборе. Кнопки LOG в проге точно нет

**Comment by merlokk** [comment]
Добавлю на следующей неделе. там надо текущую версию дотестить....   она криво работает(

**Comment by sstyle** [comment]
Здорово. Спасибо большое! Останется запилить прогу на айфон/андройд чтобы из драйва брала текущие показания и показывала. Ну и график сможет строить!

**Comment by merlokk** [comment]
там наверное надо какойто файл просто с текущими показаниями сделать - в общем посмотрю. там в конец файла долго мотать если через API

**Comment by sstyle** [comment]
да и без файла думаю что можно. в переменную записывать последнее значение, которое скрипт отсылает на драйв и его выводить через Label.

**Comment by sstyle** [comment]
типа того: http://s019.radikal.ru/i643/1504/1e/2f77db50f1e8.jpg
http://s020.radikal.ru/i700/1504/4b/78b485338dd3.jpg

**Comment by sstyle** [comment]
Еще баг заметил. Если в системе указан разделитель запятая, то он в таблицу записывает через  запятую вместо точки

**Comment by merlokk** [comment]
Разделитель и текущие показания пофиксил) https://github.com/merlokk/CO2Meter/releases/tag/RC2

**Comment by sstyle** [comment]
Спасибо! Потестирую. Хотя кроме разделителя вроде нет проблем никаких.

**Comment by sstyle** [comment]
А почему на галке стоит авто-сейв каждые 10 секунд? Он вроде раньше раз в минуту данные выгружал. За текущие значения - респект!

**Comment by merlokk** [comment]
он и так выгружает раз в минуту. это просто таймаут на повторное подключение.

**Comment by merlokk** [comment]
Вроде все) https://github.com/merlokk/CO2Meter/commit/e333c941c8b3bf2c4575276fa8a3343488c79c8a

Дальше поразвиваю немного показ истории через веб и наверное все)

**Comment by sstyle** [comment]
О, здорово. Только не понял как использовать. Куда ключ записывается и тп

**Comment by merlokk** [comment]
Там надо приложение создать и туда позапихивать файлы. После этого оно спросит разрешение. Гугл сам ключами управляет.

**Comment by sstyle** [comment]
это на script.google.com?

**Comment by sstyle** [comment]
Разобрался. Но файл index.html битый, в нем разметка испорчена

**Comment by sstyle** [comment]
Спасибо! Залил содержимое файлов, а чего дальше не ясно. Как это все теперь открыть? При создании выбирал "Web app", это верно?

**Comment by merlokk** [comment]
да. Потом Publish->Deploy as web app
оно отдаст ссылку по которой запускается

**Comment by sstyle** [comment]
открылась страничка, на ней написано "AZ 7798 CO2 datalogger" и все

**Comment by merlokk** [comment]
нет прав(

resources->advanced google services

там должно быть включено
Drive API

**Comment by sstyle** [comment]
не помогло. думается мне косяк в строке:

var files = folder.getFilesByName('current'); файл с данными то не так называется

**Comment by merlokk** [comment]
а) точно. этот файл должен быть. Его создает последний релиз.

**Comment by sstyle** [comment]
:) 
еще вопрос - а как открывать этот скрипт с айфона например? Через гугл докс откроется или как?

**Comment by merlokk** [comment]
оно при публикации ссылку дало - вот по ней оно и открывается

**Comment by sstyle** [comment]
Тогда последний вопрос - exe последнего релиза не могу найти

**Comment by merlokk** [comment]
https://github.com/merlokk/CO2Meter/releases/download/Release/OnlineLogger.7z

оно там в релизе

**Comment by sstyle** [comment]
ага, спасибо. А новые галочки, что значат? про офлайн-данные и не ждать заполнение буфера

**Comment by sstyle** [comment]
файл current появился, а вот в веб-морде изменений нет. только заголовок

**Comment by merlokk** [comment]
про офлайн-данные и не ждать заполнение буфера

это оно может вытаскивать данные за период когда не была включена программа. если на даталогере кнопку "лог" нажать

**Comment by merlokk** [comment]
а в файле current данные есть?

**Comment by sstyle** [comment]
да данные есть, одна строка и она обновляется периодически

**Comment by merlokk** [comment]
значит таки не хватает разрешений гдето(
тут https://console.developers.google.com/project есть автоматически созданный проект. в нем должны быть разрешения

**Comment by sstyle** [comment]
ну да, там все включено

**Comment by merlokk** [comment]
можно еще раз опубликовать с новой версией. оно там кеширует состояние скрипта

**Comment by sstyle** [comment]
пробовал публиковать заново. не помогает

**Comment by merlokk** [comment]
версию new ставил?

**Comment by sstyle** [comment]
ага, появилась потом 2ка индекс

**Comment by sstyle** [comment]
надо лог запилить. понять он файл то хоть видит

**Comment by merlokk** [comment]
попробуй эту ссылку
https://script.google.com/macros/s/AKfycbxerzdwaE46flCjy1iUceb3WyTxJ5EYex4oeXjdleSEFEXdknQ/exec

это я зашарил его с выполнением от пользователя

**Comment by sstyle** [comment]
Это работает

**Comment by sstyle** [comment]
Уровень ЦО космический, явно не мои данные только

**Comment by merlokk** [comment]
еще раз пересоздал. может заработает.

в общем там можно просто попробовать запрутить на отладку процедуру getContent() из code.gs и построчно туда зайти. Можно лог посмотреть - он в там в меню тоже есть

**Comment by sstyle** [comment]
Пишет что скрипт по ссылке не доступен

**Comment by sstyle** [comment]
в логе пусто. через run-> пробовал запускать обе функции.

**Comment by sstyle** [comment]
https://script.google.com/d/1xOt9PthCpbtYzjk_dypRl0pYrA9KcuPpDey1d1o9DRYXeLd2gewZj1TB/edit?usp=sharing ссылка на проект

**Comment by sstyle** [comment]
зашел еще раз в права, внизу написано что эти права должны быть включены в консоли. Нажал на ссылку, там ессно прав никаких нет. Добавил права для Drive API, Cloud sotrage и JSON. Все равно не появляется. Кроме прав может что-то еще надо там включить?

**Comment by merlokk** [comment]
ключи не нужны.

вроде все проверил в режиме дебага (там можно точку останова поставить и нажать на дебаг). Оно спросило авторизацию доступа на мой аккаунт и все отработало

**Comment by sstyle** [comment]
у меня при нажатии на дебаг снизу хочет вылезти панель и исчезает сразу. Но скрипт один хрен не работает почему то

**Comment by merlokk** [comment]
там точку останова надо поставить. слева возле номера строки мышой нажать на строке   var folders = DriveApp.getFoldersByName('CO2Meter');

**Comment by sstyle** [comment]
вот такое выдает http://s010.radikal.ru/i314/1506/4d/f4ba457fde7a.png

**Comment by merlokk** [comment]
там есть кнопочка step over - понажимай ее и посмотри доходит оно до  content = file.getAs(MimeType.PLAIN_TEXT).getDataAsString();

или не

**Comment by sstyle** [comment]
ок, жал по одной строке, дошло до этой строки. вот так http://s001.radikal.ru/i193/1506/e9/8acdcd13f14f.png

**Comment by sstyle** [comment]
вот видно что данные получает : http://s018.radikal.ru/i517/1506/40/9d47a916f7fa.png

**Comment by merlokk** [comment]
а еще раз нажми

но похоже все нормально.
странно

**Comment by merlokk** [comment]
да, данные на месте.

надо открывать консоль джаваскрипта и смотртеь почему он не может забрать
Это если в хроме - правой кнопкой на странице - просмотр кода элемента - console

**Comment by sstyle** [comment]
http://s018.radikal.ru/i501/1506/fe/a724a66bf607.png это если страница, которую получаю по deploy as web app

**Comment by merlokk** [comment]
все вроде нормально(

там еще ссылка есть в деплое "Test web app for your latest code."
может ее попробовать

**Comment by sstyle** [comment]
тоже самое. А можешь скинуть ссылку на свой проект, через шаринг в правом углу. сравню код. Все же кажется где то код кривой

**Comment by merlokk** [comment]
https://script.google.com/d/14casn12GPCZJWy9OtlWQQtdYoMfdD_1FfjuCoy1EkxgbWpYRtpB9bVgM/edit?usp=sharing

**Comment by sstyle** [comment]
Заработало. файл javascript точно другой был, надо его перезалить в исходники

**Comment by merlokk** [comment]
понятно( я залил новый html из проекта. Надо было старый залить(

а что туда добавлять?

**Comment by sstyle** [comment]
мой скрипт показывает текущую погоду на улице, прогноз погоды на 3 дня вперед, график абсолютной влажности на 4 дня (для увлажнителя важно), ниже идут графики исторические. Скрины:

http://s003.radikal.ru/i202/1506/49/d6c483ba6ca5.png
http://s020.radikal.ru/i702/1506/1e/2a63a09cf367.png

**Comment by merlokk** [comment]
прогноз я так понимаю можно с какогонить gismeteo взать

а вот над историей я еще подумаю - там не все так просто(

**Comment by sstyle** [comment]
мой скрипт историю берет с яндекса. там же и картинки и прочее.

**Comment by sstyle** [comment]
Кстати можете протестировать мой скрипт - http://az7798.orion-show.ru . Он спросит два параметра и запишет их в куки, на сервере ничего не хранится.Чтобы получить параметры надо открыть файл с данными который генерит online logger 2015_06 в гугл докс и расшарить в правом верхнем углу. Затем через File->Publish to the web получить ссылку вида: https://docs.google.com/spreadsheets/d/1Zvz1XIAIAFadvl0wk__etcbQMioAnVrMaN8e6mfmquk/pubhtml?gid=1678106385&single=true

Из нее надо взять:
key = 1Zvz1XIAIAFadvl0wk__etcbQMioAnVrMaN8e6mfmquk
и gid = 1678106385
и вбить эти (свои разуемеется) значения

**Comment by sstyle** [comment]
ссылка в почте на скрипт осталась, из поста убрал чтобы не светить

**Comment by sstyle** [comment]
исторические графики я рисую с помощью jqplot, это очень просто добавить в Ваш скрипт

**Comment by merlokk** [comment]
там их вытащить на сервере надо понять как. 
я думал использовать https://google-developers.appspot.com/chart/interactive/docs/gallery/linechart
в общем пока поразбираюсь как достать данные из файлов.

**Comment by sstyle** [comment]
ну видимо так же как и сейчас текущие значения достаете, или еще какая-то функция есть штатная чтобы читать по строкам таблицу. Нужны последние 300 строк. Их данные запихнуть в jqplot и все. Посмотрели в деле мой вариант?

**Comment by merlokk** [comment]
Посмотрел)  у меня что не работает. показывает только прогноз и влажость

**Comment by sstyle** [comment]
Крайне важно сделать обе вещи: сначала шаринг для "всех у кого ссылка" через ссылку в правом верхнем углу, а уже потом publish to the web. и шарить конкретную вкладку в файле CO2Data, а не весь документ. Кукис в браузере почистить старый, чтобы снова форма появилась

**Comment by sstyle** [comment]
Вот так:

http://s017.radikal.ru/i408/1506/d5/cae3ca0f0c3f.jpg
http://s017.radikal.ru/i436/1506/d3/6746caf28a81.jpg

**Comment by merlokk** [comment]
работает))))))))

**Comment by sstyle** [comment]
ну а как иначе то )

**Comment by sstyle** [comment]
Напрягает только раз в месяц вписывать ключи от нового файла, то есть было бы круто такой же файл иметь с постоянным именем и последними 300 строками например. Тогда один раз указал и забыл.

**Comment by merlokk** [comment]
наверно можно гугл скрипт написать который это сделает. но всеравно разбиратся с ним.

**Comment by sstyle** [comment]
ну это как файл current с текущими показаниями, но надо чтобы в нем было 300 строк.

**Comment by merlokk** [comment]
История работает) https://github.com/merlokk/CO2Meter/commit/5b313e36cd8a3700ff2701922cf50065206b0811

**Comment by sstyle** [comment]
перезалил code.gs и особо ничего не поменялось. табличка текущих данных и все. может другие файлы тоже надо поменять?

**Comment by sstyle** [comment]
заменил остальные файлы тоже, появились красивые блоки фильтры и прочее, но само окно истории пустое.

**Comment by merlokk** [comment]
Скорее всего не подключен компонент - spreadsheet.
да и должно было спросить разрешение на доступ при первом запуске

**Comment by merlokk** [comment]
чето поискал где - ненашел( хотя когда добавлял переменную в скрипт - было.
можно попробовать из отлачика запустить процедуру getHistory

**Comment by sstyle** [comment]
TypeError: Cannot call method "toString" of undefined.

**Comment by merlokk** [comment]
Похоже в скрипт на гугле не приходит дата. Похоже на то, что не все скрипты обновлены. А там календарики в полях ввода даты выскакивают?

**Comment by sstyle** [comment]
календарики выскакивают. Скрипты все обновлены точно.

**Comment by merlokk** [comment]
вроде все ок(

а опубликуй его - 
Project version: new
Execute the app as: me
Who has access to the app: anyone even anonymous

**Comment by sstyle** [comment]
опубликовал. Новую вечером залью.

**Comment by merlokk** [comment]
( а ссылку на него кинь(

**Comment by sstyle** [comment]
https://script.google.com/macros/s/AKfycbxJmU84edVKRiETzFlhRw-6UqXp16oVvl5jYakToe9boK6LZ8dq/exec

**Comment by merlokk** [comment]
баг тут
121        parseFloat(elm[2].replace(',', '.')), 

похоже что в таблице этот столбец не строка...
это температура и влажность
ща подумаю как это преобразовать

**Comment by merlokk** [comment]
попробуй - может пройдет.

**Comment by sstyle** [comment]
перезалил все файлы, все заработало! Надо над дизайном поработать в мелочах и чтобы график при загрузке показывался, а так - супер!

**Comment by merlokk** [comment]
на графике в температуре и влажности десятичные знаки показывает?

**Comment by sstyle** [comment]
нет

**Comment by merlokk** [comment]
а опубликуй его еще раз - гляну. непонятно какой тип приходит. надо наверное его залогить

**Comment by sstyle** [comment]
https://script.google.com/macros/s/AKfycbxJmU84edVKRiETzFlhRw-6UqXp16oVvl5jYakToe9boK6LZ8dq/exec

**Comment by merlokk** [comment]
все нормально)

**Comment by merlokk** [comment]
График при загрузке показывается если раскоментировать строку 109. Конфиг надо создавать, но пока только пара параметров - можно и так.
там кстати город для прогноза можно поменять в строке 20 code.gs

**Comment by sstyle** [comment]
про конфиг не понял, а остальное поковыряю, спасибо

**Comment by sstyle** [comment]
Подскажи плз, где почитать как мне адаптировать свой скрипт под этот гугл?

**Comment by merlokk** [comment]
https://github.com/merlokk/CO2Meter/blob/master/GoogleCO2Meter/JavaScript.html#L109

**Comment by merlokk** [comment]
а гугл скрипт это просто javascript c кучей засунутых туда гугловских объектов. Вот например Google Drive API https://developers.google.com/apps-script/reference/drive/  
Я никаких особых статей не читаю - просто по документации пишу и все. Хотя вполне возможно можно найти чето почитать или скорее посмотреть вебинар на тему гугл скрипта.
