### ISSUE TITLE
Постоянно спрашивает разрешения в гугл на Win8 x64

### ISSUE THREAD

**Issue by sstyle** [merlokk/CO2Meter#9]
Чистая винда, поставил прогу. Показывает цифры с девайса, ключи ввел. Показывает окно разрешить доступ, жму принять, сразу же снова выскакивает и так бесконечно (

**Comment by merlokk** [comment]
А если его запустить под админом? Тоже самое?

**Comment by sstyle** [comment]
та же фигня. пробовал сразу же

**Comment by merlokk** [comment]
дойду до 10-ки погляжу. Скорее всего там разница в браузере....   наверное просто не передается ключ

**Comment by sstyle** [comment]
как успехи?

**Comment by sstyle** [comment]
??

**Comment by merlokk** [comment]
Я за границей. Буду через 2 недели примерно)

**Comment by sstyle** [comment]
а ок ) Забугорье это хорошо

**Comment by sstyle** [comment]
Напомню о себе ) А то без Вашей проги очень туго, уже увлажнители включил все

**Comment by merlokk** [comment]
Нашел какуюто багу... не факт че оно...

у меня на 10ке все работает(
там надо убрать расширение docx

если не получится - наверное надо будет логирование добавлять(

[OnlineLogger.7z.docx](https://github.com/merlokk/CO2Meter/files/18517/OnlineLogger.7z.docx)

**Comment by sstyle** [comment]
Похоже что помогло! Прога запустилась и спросила один раз, но надо 7798 подключить еще проверить, а я не дома. Вечерком отпишусь

**Comment by sstyle** [comment]
нифига не помогло :(

**Comment by merlokk** [comment]
А оно если без подключения 7778 только 1 раз спрашивает?

а и еще....
в файле logger.ini в строчках ниже токен есть? 
[Security]
RefreshToken=#########token############

**Comment by sstyle** [comment]
токена нет. если без подключения то 1 раз.

**Comment by merlokk** [comment]
не может получить токен(
 лог напишу - закину тест.

**Comment by sstyle** [comment]
ок спасибо!

**Comment by sstyle** [comment]
я вот думаю, может дело в настройках IE? или версии? у меня 10й стоит. Может служба какая-то отключена или еще что. Винда MSDN, не сборка, поставлена начисто была недавно.

**Comment by sstyle** [comment]
вот еще что пишут http://stackoverflow.com/questions/26549687/oauth-2-0-to-access-google-apis-not-working-in-ie

**Comment by merlokk** [comment]
Там оно переходит по страницам пока не дойдет до кода. может быть оно просто туда не доходит почемуто.  наверно можно было попробовать просто попереходить в браузере, но помоему там пост запрос
(

**Comment by sstyle** [comment]
без 7798 тоже кучу раз спрашивает, если нажать на "сохранить в облако один раз"

**Comment by sstyle** [comment]
сейчас скачал прогу для гугл диск https://www.insynchq.com. Она поставилась, спросила разрешение как сабж (правда открыла сам браузер) и заработала без вопросов. Браузер спрашивал давать ли этой проге добро на доступ к доверенному сайту? Я сказал да и все получилось. Может в этом дело? Надо прогу добавить в доверенные?

**Comment by sstyle** [comment]
поставил 10ку. Та же фигня. MSDN Pro.

**Comment by sstyle** [comment]
:(

**Comment by merlokk** [comment]
Опять не дома.... Буду только 16го. Похоже, что просто перекомпилировать надо под 10 кой. Можно еще отключить брандмауэр.

**Comment by sstyle** [comment]
Брендмауэр выключен

**Comment by sstyle** [comment]
привет. есть новости?

**Comment by sstyle** [comment]
........

**Comment by sstyle** [comment]
Ау (

**Comment by sstyle** [comment]
я все еще не теряю надежды на исправление бага

**Comment by sstyle** [comment]
Обидно, что автор кинул с решением проблемы. Но разобрался сам благодаря старой-старой версии OnlineLogger. В винде по дефолту не установлен OpenSSL, на что винда благополучно ругается в старой версии, а в новой нет. Без проблем получил токен на XP с OpenSSL. На 10ке пока не очень получается, но подсунув logger.ini из ХР в 10ку все итак работает.
